name: max_moments
description: Print dialog for thermal-printer plugin.
homepage: https://github.com/tothemaxdevs/max_moments
version: 1.0.1+9

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # cached_video_player: ^2.0.4
  flutter_svg: ^2.0.5
  dio: ^5.4.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  flutter_cached_video_player_plus: ^2.1.3
  getwidget: ^4.0.0
  http_parser: ^4.0.2
  video_trimmer: ^3.0.1
  flutter_spinkit: ^5.2.1
  file_picker: ^8.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/
